spring:
  application:
    name: item-service

server:
  port: 8001

  rabbitmq:
    host: 172.16.112.248
    port: 5672
    username: admin
    password: admin
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka
      
  cloud:
    config:
      override-none: true
      
      
