spring:
  application:
    name: order-service

  rabbitmq:
    host: 172.16.112.248
    port: 5672
    username: admin
    password: admin
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka
      
#---
#spring:
  #profiles: order1
  
server:
  port: 8201

#---

#spring:
  #profiles: order2
  
#server:
 # port: 8202
  
feign:
  hystrix:
    enabled: true
    
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream